### ISSUE TITLE
Mondrian UnsupportedOperationException on XMLAMember.getChildren()

### ISSUE THREAD

**Issue by RogerWebb** [may-day/olap#4]
I am attempting to crawl a hierarchy and am getting an error whenever I attempt to call "getChildren" on any XMLAMember.  I've tried pulling members from a Hierarchy and a Level.  The results are the same.

I've provided what I believe to be all relevant environment/context, but I'm happy to provide anything I'm able on request.  From what I can tell, Mondrian is not liking the XML/A request coming from the library.  Not sure if it's something that you're aware of, or if it's something that can be worked around.

I appreciate any help you're willing/able to provide.

Python Version:  2.7.3

Package Version (from "pip freeze"):  xmla==0.7.2

Mondrian Version:  3.9

Example Code (sensitive information has been replaced.  example output below)

```python
import olap.xmla.xmla as xmla

location = "http://mondrian.example.com:8080/pentaho/Xmla"
username = "username"
password = "password"

xmla_provider = xmla.XMLAProvider()

xmla_connection = xmla_provider.connect(location=location, username=username, password=password)

olap_source = xmla_connection.getOLAPSource()

h = olap_source.getCatalog('MyCatalog').getCube('Click').getDimension('[Vendor]').getHierarchy('[Vendor]')

for member in h.getMembers():
    print "Member: %s" % member.getUniqueName()

    if member.hasChildren():
        #ERROR OCCURS WHEN EXECUTING NEXT LINE
        for child in member.getChildren():
            print "Child: %s" % child.getUniqueName()

```

OUTPUT:

```
No handlers could be found for logger "olap.xmla.requests_kerberosauth"
Member: [Vendor].[All Vendors]
Traceback (most recent call last):
  File "bug.py", line 19, in <module>
    for child in member.getChildren():
  File "/usr/local/lib/python2.7/dist-packages/olap/xmla/xmla.py", line 276, in getChildren
    more_restrictions={"TREE_OP":TREE_OP.CHILDREN})
  File "/usr/local/lib/python2.7/dist-packages/olap/xmla/xmla.py", line 101, in getSchemaElements
    props = func(r, properties)
  File "/usr/local/lib/python2.7/dist-packages/olap/xmla/connection.py", line 67, in <lambda>
    *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/olap/xmla/connection.py", line 109, in Discover
    raise XMLAException(fault.message, dictify(fault.fault))
olap.xmla.interfaces.XMLAException: Server raised fault: 'XMLA Discover unparse results error'
```

MONDRIAN Exception (from bi-server/tomcat/logs/pentaho.log)

```
2015-05-29 10:51:29,814 ERROR [mondrian.xmla.XmlaServlet] Errors when handling XML/A message
mondrian.xmla.XmlaException: Mondrian Error:XMLA Discover unparse results error
        at mondrian.xmla.XmlaHandler.discover(XmlaHandler.java:2873)
        at mondrian.xmla.XmlaHandler.process(XmlaHandler.java:671)
        at mondrian.xmla.impl.DefaultXmlaServlet.handleSoapBody(DefaultXmlaServlet.java:507)
        at mondrian.xmla.XmlaServlet.doPost(XmlaServlet.java:318)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
...
Caused by: java.lang.UnsupportedOperationException
        at mondrian.xmla.RowsetDefinition$SharedDimensionHolderCube.lookupMember(RowsetDefinition.java:6552)
        at mondrian.xmla.RowsetDefinition$MdschemaMembersRowset.outputUniqueMemberName(RowsetDefinition.java:5711)
        at mondrian.xmla.RowsetDefinition$MdschemaMembersRowset.populateCatalog(RowsetDefinition.java:5476)
        at mondrian.xmla.RowsetDefinition$MdschemaMembersRowset.populateImpl(RowsetDefinition.java:5459)
        at mondrian.xmla.Rowset.populate(Rowset.java:222)
        at mondrian.xmla.Rowset.unparse(Rowset.java:194)
        at mondrian.xmla.XmlaHandler.discover(XmlaHandler.java:2867)

```

...

**Comment by may-day** [comment]
Umm yes, there are actually a few problems:
1) the lib only passes the current elements unique name as the single constraint in getHierarchies, getMembers or getChildren. It should also set it's parents' unique names. Otherwise elements are returned multiple times in case they are shared among multiple cubes.
2) apparently it has a problem with ragged hierarchies, although i'm not sure yet what's the root cause here.

Anyway, for now i can only show, how you can walk through the structure, for example with the foodmart catalog - adapt to your catalog as needed:
```python

import olap.xmla.xmla as xmla
import sys

location = "http://localhost:8080/mondrian/xmla"
xmla_provider = xmla.XMLAProvider()

xmla_connection = xmla_provider.connect(location=location)

olap_source = xmla_connection.getOLAPSource()
cat = olap_source.getCatalog('FoodMart')

def getDimensions(c, cube_name):
    return c.getSchemaElements("DIMENSION", 
                               None,
                               aslist=True, 
                               more_restrictions={"CUBE_NAME":cube_name})

def getHierarchies(d, cube_name, dim_name):
    return d.getSchemaElements("HIERARCHY", 
                               None,
                               aslist=True, 
                               more_restrictions={"CUBE_NAME":cube_name, "DIMENSION_UNIQUE_NAME":dim_name})

def getMembers(h, cube_name, dim_name, hier_name):
    return h.getSchemaElements("HIERARCHY_MEMBER", 
                               None,
                               aslist=True, 
                               more_restrictions={"CUBE_NAME":cube_name, "DIMENSION_UNIQUE_NAME":dim_name, "HIERARCHY_UNIQUE_NAME":hier_name})

def getChildren(m, cube_name, dim_name, hier_name, member_name):
    return m.getSchemaElements("TREE_MEMBER", 
                               None,
                               aslist=True, 
                               more_restrictions={"TREE_OP":1, "CUBE_NAME":cube_name, "DIMENSION_UNIQUE_NAME":dim_name, "HIERARCHY_UNIQUE_NAME":hier_name, "MEMBER_UNIQUE_NAME":member_name})


for cube in cat.getCubes():
  cube_name = cube.CUBE_NAME
  for dim in getDimensions(cube, cube_name):
    dim_name = dim.DIMENSION_UNIQUE_NAME
    for hier in getHierarchies(dim, cube_name, dim_name):
      hier_name = hier.HIERARCHY_UNIQUE_NAME
      for m in getMembers(hier, cube_name, dim_name, hier_name):
        member_name = m.MEMBER_UNIQUE_NAME
        if m.hasChildren():
          i=0
          try:
             for child in getChildren(m, cube_name, dim_name, hier_name, member_name):
                 i+=1
                 #print child
                 
          except Exception, e:
              print e
              print >> sys.stderr, "******** bombed at child ",i," ************"
              print >> sys.stderr, cube
              print >> sys.stderr, dim
              print >> sys.stderr, hier
              print >> sys.stderr, m
              print >> sys.stderr, e
              print cube_name, dim_name, hier_name, member_name
```

If you run this with the foodmart catalog, you'll see it throwing exceptions in the "Sales Ragged" Cube - still not sure why - even the Exception are empty .. odd.
